name = "InfoMap"
uuid = "0d535278-ea44-4e2c-a7c0-8a956e8c27a1"
authors = ["RandyRDavila <randyrdavila@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
